// Copy for the fleet workspace, in the console's two languages.

export type Lang = 'en' | 'id';

const en = {
  fleet: 'Fleet',
  device: 'Device',
  units: 'units',
  moving: 'Moving',
  idle: 'Idle',
  parked: 'Parked',
  silent: 'Silent',
  stopped: 'Stopped',
  delivery: 'Delivery to Hexa.Sensor',
  sent: 'sent',
  rejected: 'rejected',
  failed: 'failed',
  queued: 'queued',
  notConfigured: 'Not configured on this server',
  lastError: 'Last error',
  timeline: 'Timeline',
  start: 'Start',
  stop: 'Stop',
  restart: 'Restart',
  next: 'Next',
  inTime: 'in',
  finished: 'Finished',
  noTimeline: 'No timeline running. Reset to T0 first for a run that plays the same every time.',
  group: 'Apply to a group',
  anyKind: 'Every kind',
  anyEstate: 'Every estate',
  anyOutput: 'Every output',
  behaviour: 'Behaviour',
  minutes: 'min',
  apply: 'Apply',
  routeTo: 'Send over',
  setOutput: 'Route',
  clear: 'Clear behaviours',
  match: 'units match',
  resetT0: 'Reset to T0',
  resetConfirm: 'Click again to put every unit back at its starting point, end all behaviours and stop the timeline.',
  resetAgain: 'Click again to reset',
  exportSensor: 'Export for Hexa.Sensor',
  exportHint: 'Device types and the four CSV imports. Import again any time: nothing changes twice.',
  output: 'Output',
  ready: 'Ready',
  sending: 'Sending',
  error: 'Error',
  notSent: 'Not sent',
  now: 'Now',
  speed: 'Speed',
  heading: 'Heading',
  ignition: 'Ignition',
  position: 'Position',
  on: 'On',
  off: 'Off',
  yes: 'Yes',
  no: 'No',
  externalPower: 'Vehicle power',
  battery: 'Tracker battery',
  gsm: 'GSM signal',
  gnss: 'GNSS',
  odometer: 'Odometer',
  implement: 'Implement',
  implementDown: 'Down (working)',
  implementUp: 'Up',
  powerCut: 'Power cut',
  behaviours: 'Behaviours',
  active: 'Active',
  scheduled: 'Scheduled',
  endsIn: 'ends in',
  startsIn: 'starts in',
  noBehaviours: 'Running its normal day.',
  given: 'given to',
  estate: 'Estate',
  kind: 'Kind',
  fix: 'Fix',
  noFix: 'No fix',
  rejectedHint: 'Hexa.Sensor refuses this unit. Import the fleet package into Sensor to register it.',
  outputChanged: 'now sends over',
  applied: 'applied to',
  cleared: 'behaviours cleared',
  routed: 'units routed to',
  resetDone: 'Fleet reset to T0',
  scenarioStarted: 'Timeline started',
  scenarioStopped: 'Timeline stopped',
  close: 'Close',
};

const id: typeof en = {
  fleet: 'Armada',
  device: 'Perangkat',
  units: 'unit',
  moving: 'Bergerak',
  idle: 'Idle',
  parked: 'Parkir',
  silent: 'Senyap',
  stopped: 'Berhenti',
  delivery: 'Pengiriman ke Hexa.Sensor',
  sent: 'terkirim',
  rejected: 'ditolak',
  failed: 'gagal',
  queued: 'antre',
  notConfigured: 'Belum dikonfigurasi di server ini',
  lastError: 'Error terakhir',
  timeline: 'Linimasa',
  start: 'Mulai',
  stop: 'Hentikan',
  restart: 'Ulangi',
  next: 'Berikutnya',
  inTime: 'dalam',
  finished: 'Selesai',
  noTimeline: 'Tidak ada linimasa berjalan. Reset ke T0 dulu agar setiap putaran berjalan sama.',
  group: 'Terapkan ke grup',
  anyKind: 'Semua jenis',
  anyEstate: 'Semua estate',
  anyOutput: 'Semua output',
  behaviour: 'Perilaku',
  minutes: 'mnt',
  apply: 'Terapkan',
  routeTo: 'Kirim lewat',
  setOutput: 'Arahkan',
  clear: 'Hapus perilaku',
  match: 'unit cocok',
  resetT0: 'Reset ke T0',
  resetConfirm: 'Klik lagi untuk mengembalikan setiap unit ke titik awal, mengakhiri semua perilaku, dan menghentikan linimasa.',
  resetAgain: 'Klik lagi untuk reset',
  exportSensor: 'Ekspor untuk Hexa.Sensor',
  exportHint: 'Tipe perangkat dan empat impor CSV. Aman diimpor ulang: tidak ada yang berubah dua kali.',
  output: 'Output',
  ready: 'Siap',
  sending: 'Mengirim',
  error: 'Error',
  notSent: 'Tidak dikirim',
  now: 'Sekarang',
  speed: 'Kecepatan',
  heading: 'Arah',
  ignition: 'Kontak',
  position: 'Posisi',
  on: 'Nyala',
  off: 'Mati',
  yes: 'Ya',
  no: 'Tidak',
  externalPower: 'Daya kendaraan',
  battery: 'Baterai tracker',
  gsm: 'Sinyal GSM',
  gnss: 'GNSS',
  odometer: 'Odometer',
  implement: 'Implemen',
  implementDown: 'Turun (bekerja)',
  implementUp: 'Naik',
  powerCut: 'Daya terputus',
  behaviours: 'Perilaku',
  active: 'Aktif',
  scheduled: 'Terjadwal',
  endsIn: 'berakhir dalam',
  startsIn: 'mulai dalam',
  noBehaviours: 'Menjalani hari normalnya.',
  given: 'diberikan ke',
  estate: 'Estate',
  kind: 'Jenis',
  fix: 'Fix',
  noFix: 'Tanpa fix',
  rejectedHint: 'Hexa.Sensor menolak unit ini. Impor paket armada ke Sensor untuk mendaftarkannya.',
  outputChanged: 'sekarang mengirim lewat',
  applied: 'diterapkan ke',
  cleared: 'perilaku dihapus',
  routed: 'unit diarahkan ke',
  resetDone: 'Armada di-reset ke T0',
  scenarioStarted: 'Linimasa dimulai',
  scenarioStopped: 'Linimasa dihentikan',
  close: 'Tutup',
};

export function fleetCopy(lang: Lang) {
  return lang === 'id' ? id : en;
}

const kindNames: Record<Lang, Record<string, string>> = {
  en: { 'haul-truck': 'Haul truck', 'farm-tractor': 'Farm tractor', dozer: 'Dozer', excavator: 'Excavator', pickup: 'Pickup', 'water-truck': 'Water truck', 'fuel-bowser': 'Fuel bowser' },
  id: { 'haul-truck': 'Truk angkut', 'farm-tractor': 'Traktor', dozer: 'Dozer', excavator: 'Ekskavator', pickup: 'Pikap', 'water-truck': 'Truk air', 'fuel-bowser': 'Truk BBM' },
};

export function kindName(lang: Lang, key: string): string {
  return kindNames[lang][key] ?? key;
}

const behaviourNames: Record<Lang, Record<string, string>> = {
  en: { overspeed: 'Overspeed', 'geofence-exit': 'Leave the area', 'signal-loss': 'Signal loss', intermittent: 'Intermittent', 'power-cut': 'Power cut', idle: 'Idle', park: 'Park', work: 'Work a compartment' },
  id: { overspeed: 'Ngebut', 'geofence-exit': 'Keluar area', 'signal-loss': 'Hilang sinyal', intermittent: 'Putus-putus', 'power-cut': 'Daya terputus', idle: 'Idle', park: 'Parkir', work: 'Kerjakan kompartemen' },
};

export function behaviourName(lang: Lang, type: string): string {
  return behaviourNames[lang][type] ?? type;
}

/** m:ss or h:mm:ss for a number of seconds. */
export function clock(seconds: number): string {
  const s = Math.max(0, Math.round(seconds));
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  const r = String(s % 60).padStart(2, '0');
  return h > 0 ? `${h}:${String(m).padStart(2, '0')}:${r}` : `${m}:${r}`;
}
