-- Superseded by 004_fleet.sql. This migration used to insert a 350-truck grid whose IMEIs
-- (35630704244xxxx) collide with Hexa.Sensor's own simulator fleet. The API now seeds the demo
-- fleet from its composition at startup (internal/fleet), so this file does nothing. It stays
-- because scripts/migrate.sh applies every file in order.
