schema: hexa.build/project/v1
name: hexa-simulator
adapter: .hexa/project
environment:
  pass:
    - DATABASE_URL
    - TEST_DATABASE_URL
    - RUNTIME_ENV_FILE
    - SIM_SENSOR_PUSH_URL
    - SIM_SENSOR_PUSH_KEY
    - SIM_SENSOR_PUSH_TIMEOUT
    - SIM_ADMIN_USERNAME
    - SIM_ADMIN_PASSWORD
    - SIM_SECURITY_KEY
    - TELTONIKA_GATEWAY_ADDR
    - TELTONIKA_GATEWAY_TIMEOUT
    - TELTONIKA_CODEC
    - SIM_MQTT_URL
    - SIM_MQTT_TOPIC
    - SIM_MQTT_TIMEOUT
